### ISSUE TITLE
Header files: No such file or directort during make command

### ISSUE THREAD

**Issue by carpekd** [usnistgov/STP2X3D#1]
I'm getting the following error when using the make command:

```
/home/ec2-user/environment/STP2X3D/STP2X3D/OCCLib.h:21:10: fatal error: Poly.hxx: No such file or directory
 #include <Poly.hxx>
          ^~~~~~~~~~
compilation terminated.
make[2]: *** [STP2X3D/CMakeFiles/STP2X3D.dir/Component.cpp.o] Error 1
make[1]: *** [STP2X3D/CMakeFiles/STP2X3D.dir/all] Error 2
make: *** [all] Error 2
```

I've installed OCCT 7.4.0 successfully, and my includes are located in the following directory:

`/usr/local/include/opencascade`

How can I point to the right directory for the header files?  I am installing on Linux.

**Comment by carpekd** [comment]
I copied the header files from /usr/local/include/opencascade to /usr/local/include to correct the issue

**Comment by tejpochiraju** [comment]
A less drastic solution would be to temporarily change the include paths with:

`
CPATH=/usr/local/include/opencascade/ make
`
