### ISSUE TITLE
error: ‘class TCollection_ExtendedString’ has no member named ‘ToWideString’

### ISSUE THREAD

**Issue by carpekd** [usnistgov/STP2X3D#2]
When running the make command,  I get the following error:

```
/home/ec2-user/environment/STP2X3D/STP2X3D/STEP_Reader.cpp: In member function ‘std::wstring STEP_Reader::GetName(const TDF_Label&) const’:
/home/ec2-user/environment/STP2X3D/STP2X3D/STEP_Reader.cpp:229:26: error: ‘class TCollection_ExtendedString’ has no member named ‘ToWideString’; did you mean ‘ToExtString’?
  wstring name = nameText.ToWideString();
                          ^~~~~~~~~~~~
                          ToExtString
make[2]: *** [STP2X3D/CMakeFiles/STP2X3D.dir/STEP_Reader.cpp.o] Error 1
make[1]: *** [STP2X3D/CMakeFiles/STP2X3D.dir/all] Error 2
make: *** [all] Error 2
```

I have installed OCCT 7.4.0, and I am running cmake 3.18 on AWS Linux 2.

**Comment by tejpochiraju** [comment]
Just tried building this on Ubuntu 20.04 and ran into the same issue. 

A bit more digging reveals that `toWideString` is a Windows specific function to convert to UTF-16. This is not relevant on Linux as per a similar modification made in the [pyOCCT project](https://github.com/trelau/pyOCCT/pull/41/commits/21f9a661fa474387cc2b56576aad3ba1f81d1929#diff-a0cc1db1fccfeab3f5131631ef5b2dbaR104)

I am just starting to see what changes need to be made to this project to make it suitable for compiling on Linux.

**Comment by carpekd** [comment]
Great, I look forward to the progress. Thanks

**Comment by soonjokwon** [comment]
@carpekd 
My answer is the same as the one above. 
The member function "ToWideString" is supported in Windows only.

@tejpochiraju 
Thanks for your answer on this issue.
Please let me know if you have a suggestion.

**Comment by soonjokwon** [comment]
This one is resolved.
