### ISSUE TITLE
Missing Linux build (Ubuntu 20.04 LTS)

### ISSUE THREAD

**Issue by alekssadowski95** [usnistgov/STP2X3D#5]
Is it possible to add a Ubuntu 20.04 LTS build to the releases? The reason I am asking is beacuse I am not able to do it myself, as I dont understand how OCCT works.

**Comment by soonjokwon** [comment]
I'm sorry but I'm not planning on building it on a Linux machine at this moment.
You can try building OCCT in a Linux environment. Please check the link below.

https://dev.opencascade.org/doc/occt-7.6.0/overview/html/build_upgrade__building_occt.html

I hope this helps.
