### ISSUE TITLE
Cannot display GD&T information

### ISSUE THREAD

**Issue by totaldmis** [usnistgov/STP2X3D#7]
I compiled the latest STP2X3D (VS2022+OCC7.6), and tested the file "nist_ctc_01_asme1_ap242.stp". The html generated by the STP2X3D only displays the CAD model, and does not display the corresponding GD&T data. But the strange thing is, using the "STEP File Analyzer and Viewer" can display the correct GD&T information. The attached file is the file I teste. 
[nist_ctc_01_asme1_ap242.zip](https://github.com/usnistgov/STP2X3D/files/7733296/nist_ctc_01_asme1_ap242.zip)

How can I solve the problem? Thank you

**Comment by soonjokwon** [comment]
Hi,

What you need to know is STP2X3D translates and highlights "**geometries related to GD&T**" such as faces and edges (See the figure below).
STP2X3D does not translate **the presentation PMIs** that you expect which can be obtained by SFA.
This is because OCCT does not successfully translate the presentation PMIs at the moment. Once OCCT fully supports it, it may be integrated into STP2X3D.
The SFA developer is planning on linking the presentation PMI with relevant geometries for cross-highlighting.

Please test with the latest code that's just been committed.

![image](https://user-images.githubusercontent.com/67339153/146534537-a0fe433f-4cc7-4571-8701-947874abe5a6.png)

**Comment by totaldmis** [comment]
Okay, I see. Thank you for your reply

**Comment by akjay** [comment]
So how to display the GD&T information with SFA?Not familiar with the tcl language.Is the "sfa-geotol.tcl" file to do this thing？
As far as I know, OCC can get some GD&T representation from STEP AP242 file like "nist_ctc_05.stp" download with SFA，but sometimes, when I draw my own step file with Solidworks 2021 and mark some GD&T information,then open with OCC,it can not shown GD&T representation,but SFA can display what I marked in Solidworks.So I wonder how to makes it？

**Comment by soonjokwon** [comment]
@akjay 
1. OCC currently fails to process some STEP entities used to represent GD&T presentation.
In other words, as far as I know, different CAD systems use different STEP entities to represent GD&T presentation, and only one of them can be processed by OCC at present.
Please refer to the following link regarding the issue you mentioned.
[Link](https://dev.opencascade.org/content/unable-get-complextriangulatedsurfaceset-graphical-pmi-shapes-step-file#comment-22397)

2. SFA does not use OCC for processing GD&T presentation.

**Comment by akjay** [comment]
> @akjay 
> 1. OCC currently fails to process some STEP entities used to represent GD&T presentations.
> In other words, as far as I know, different CAD systems use different STEP entities to represent GD&T presentation, and only one of them can be processed by OCC at present.
> Please refer to the following link regarding the issue you mentioned.
> [Link](https://dev.opencascade.org/content/unable-get-complextriangulatedsurfaceset-graphical-pmi-shapes-step-file#comment-22397)
> 
> 2. SFA does not use OCC for processing GD&T presentations. The developer has written its own code to do it.

OK，learn it.Thank you for reply.

**Comment by akjay** [comment]
> > @akjay 
> > 1. OCC currently fails to process some STEP entities used to represent GD&T presentations.
> > In other words, as far as I know, different CAD systems use different STEP entities to represent GD&T presentation, and only one of them can be processed by OCC at present.
> > Please refer to the following link regarding the issue you mentioned.
> > [Link](https://dev.opencascade.org/content/unable-get-complextriangulatedsurfaceset-graphical-pmi-shapes-step-file#comment-22397)
> > 
> > 2. SFA does not use OCC for processing GD&T presentations. The developer has written its own code to do it.
> 
> OK，learn it.Thank you for reply.By the way
，the part 2 SFA write its own code to do the GD&T presentations process is open source or not？

**Comment by soonjokwon** [comment]
@akjay 
Please check the below
https://github.com/usnistgov/SFA

**Comment by akjay** [comment]
> @akjay 
> Please check the below
> https://github.com/usnistgov/SFA

Ok，thank you.
